/*Schema for creating a table of users*/
CREATE TABLE `tbl_user` (
  `USER_ID` int(11) NOT NULL AUTO_INCREMENT,
  `USER_NAME` varchar(45) NOT NULL,
  `PASSWORD` varchar(45) NOT NULL,
  `USERTYPE` varchar(45) NOT NULL,
  PRIMARY KEY (`USER_ID`),
  UNIQUE KEY `USER_ID_UNIQUE` (`USER_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8;


/*Schema for creating a stock record table*/
CREATE TABLE `tbl_record` (
  `REC_ID` int(12) unsigned zerofill NOT NULL,
  `REC_NAME` varchar(45) NOT NULL,
  `REC_CATEGORY_ID` int(11) NOT NULL,
  `REC_SELL` double NOT NULL,
  `REC_CASH` double NOT NULL,
  `REC_EXCHANGE` double NOT NULL,
  `REC_NOTE` varchar(1000) DEFAULT NULL,
  `REC_KEYWORDS` varchar(1000) DEFAULT NULL,
  `REC_REQ_SERIAL` tinyint(1) NOT NULL,
  `REC_REQ_TEST` tinyint(1) NOT NULL,
  `REC_SEARCHTERMS` varchar(1000) DEFAULT NULL,
  PRIMARY KEY (`REC_ID`),
  UNIQUE KEY `REC_ID_UNIQUE` (`REC_ID`),
  KEY `FK_CATEGORY_ID_idx` (`REC_CATEGORY_ID`),
  CONSTRAINT `FK_CATEGORY_ID` FOREIGN KEY (`REC_CATEGORY_ID`) REFERENCES `tbl_category` (`CAT_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

  
  /*Schema for creating a stock item table*/
CREATE TABLE `tbl_stock` (
  `STOCK_ID` int(11) NOT NULL AUTO_INCREMENT,
  `STOCK_REC_ID` int(11) NOT NULL,
  `STOCK_NAME` varchar(45) NOT NULL,
  `STOCK_SERIAL` varchar(45) DEFAULT NULL,
  `STOCK_IS_FAULTY` int(11) NOT NULL,
  `STOCK_FAULT_NOTE` varchar(45) DEFAULT NULL,
  `STOCK_HAS_SOLD` int(11) NOT NULL,
  `STOCK_SOLD_CASH` int(11) DEFAULT NULL,
  `STOCK_BOUGHT_CASH` int(11) DEFAULT NULL,
  `STOCK_BOUGHT_EXCHANGE` int(11) DEFAULT NULL,
  PRIMARY KEY (`STOCK_ID`),
  UNIQUE KEY `STOCK_ID_UNIQUE` (`STOCK_ID`),
  KEY `FK_StockRecordID_idx` (`STOCK_REC_ID`),
  CONSTRAINT `FK_StockRecordID` FOREIGN KEY (`STOCK_REC_ID`) REFERENCES `tbl_record` (`REC_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

  
  /*Schema for creating a category table*/
CREATE TABLE `tbl_category` (
  `CAT_ID` int(11) NOT NULL AUTO_INCREMENT,
  `CAT_NAME` varchar(45) NOT NULL,
  PRIMARY KEY (`CAT_ID`),
  UNIQUE KEY `REC_CATEGORY_UNIQUE` (`CAT_NAME`),
  UNIQUE KEY `REC_ID_UNIQUE` (`CAT_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=26 DEFAULT CHARSET=utf8;

  
  /*SQL to add Stock Record's ID as a foreign key to Stock Item table*/   
  ALTER TABLE `webpos`.`tbl_stock` 
ADD INDEX `FK_StockRecordID_idx` (`STOCK_REC_ID` ASC);
ALTER TABLE `webpos`.`tbl_stock` 
ADD CONSTRAINT `FK_StockRecordID`
  FOREIGN KEY (`STOCK_REC_ID`)
  REFERENCES `webpos`.`tbl_record` (`REC_ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

