/*Schema for creating a table of users*/
CREATE TABLE `tbl_user` (
  `USER_ID` int(11) NOT NULL AUTO_INCREMENT,
  `USER_NAME` varchar(45) NOT NULL,
  `PASSWORD` varchar(45) NOT NULL,
  `USERTYPE` int(11) NOT NULL,
  PRIMARY KEY (`USER_ID`),
  UNIQUE KEY `USER_ID_UNIQUE` (`USER_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;

/*Schema for creating a stock record table*/
CREATE TABLE `webpos`.`tbl_record` (
  `REC_ID` INT NOT NULL AUTO_INCREMENT,
  `REC_NAME` VARCHAR(45) NOT NULL,
  `REC_CATEGORY` INT NOT NULL,
  `REC_SELL` DOUBLE NOT NULL,
  `REC_CASH` DOUBLE NOT NULL,
  `REC_EXCHANGE` DOUBLE NOT NULL,
  `REC_NOTE` VARCHAR(45) NULL,
  `REC_KEYWORDS` VARCHAR(45) NULL,
  `REC_REQ_SERIAL` INT NOT NULL,
  `REC_REQ_TEST` INT NOT NULL,
  PRIMARY KEY (`REC_ID`),
  UNIQUE INDEX `REC_ID_UNIQUE` (`REC_ID` ASC));
  
  /*Schema for creating a stock item table*/
  CREATE TABLE `webpos`.`tbl_stock` (
  `STOCK_ID` INT NOT NULL AUTO_INCREMENT,
  `STOCK_REC_ID` INT NOT NULL,
  `STOCK_NAME` VARCHAR(45) NOT NULL,
  `STOCK_SERIAL` VARCHAR(45) NULL,
  `STOCK_IS_FAULTY` INT NOT NULL,
  `STOCK_FAULT_NOTE` VARCHAR(45) NULL,
  `STOCK_HAS_SOLD` INT NOT NULL, 
  `STOCK_SOLD_CASH` INT NULL, /*Amount item was sold for*/
  `STOCK_BOUGHT_CASH` INT NULL, /*Amount item was bought for*/
  `STOCK_BOUGHT_EXCHANGE` INT NULL, /*Amount item was exchanged for*/
  PRIMARY KEY (`STOCK_ID`),
  UNIQUE INDEX `STOCK_ID_UNIQUE` (`STOCK_ID` ASC));
  
  /*SQL to add Stock Record's ID as a foreign key to Stock Item table*/   
  ALTER TABLE `webpos`.`tbl_stock` 
ADD INDEX `FK_StockRecordID_idx` (`STOCK_REC_ID` ASC);
ALTER TABLE `webpos`.`tbl_stock` 
ADD CONSTRAINT `FK_StockRecordID`
  FOREIGN KEY (`STOCK_REC_ID`)
  REFERENCES `webpos`.`tbl_record` (`REC_ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

